id: A8399F1F6
base_file: fA9F0.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:17:37.204844
  last_modified_at: 2022-05-30 22:17:37.204851
